### ISSUE TITLE
Install Error: human_final_3D_distance_data.tsv

### ISSUE THREAD

**Issue by hsn-ylmz** [fallerlab/ARF#1]
During installation process I'm getting this error message:

   cp: cannot stat 'fallerlab-ARF-7b9e8ec/data-raw/human_final_3D_distance_data.tsv': No such file or directory
   cp: cannot stat 'fallerlab-ARF-7b9e8ec/data-raw/mouse_final_3D_distance_data.tsv': No such file or directory
    ERROR
   copying to build directory failed

It seems you didn't upload these files or I cannot download from github. Can you help me about this?

**Comment by ferhatalkan** [comment]
Sorry about that. Now I pushed the missing files. Let me know if it doesn't work.
