### ISSUE TITLE
GSEA analysis error

### ISSUE THREAD

**Issue by jasons2389** [fallerlab/ARF#2]
Hello!
I am running the pipeline, but when I get to the GSEA analysis is gives me this error:
Error in if (abs(max.ES) > abs(min.ES)) { : 
  missing value where TRUE/FALSE needed

If I run the pipeline with only two group I don't get the error. 
Do you know what could be the problem?

**Comment by ferhatalkan** [comment]
Hi, I'm not sure right away about what could cause this. How many samples and groups do u provide when you get the error?

**Comment by jasons2389** [comment]
Hi, I am proving six samples with three groups. (2 samples per group)

**Comment by ferhatalkan** [comment]
Are you running the dripARF() wrapper or dripARF_predict_heterogenity() function? I will do some tests with same settings and get back here.

**Comment by jasons2389** [comment]
I am using the predict heterogeneity function. Thanks!

**Comment by ferhatalkan** [comment]
Did you try the wrapper" Does it give the same error?

**Comment by ferhatalkan** [comment]
I could not generate the same error using the same function with 6 samples (2 per group) myself, therefore, I'm not sure what went wrong in your run.
