### ISSUE TITLE
RP-rRNA proximity sets

### ISSUE THREAD

**Issue by junsoopablo** [fallerlab/ARF#3]
Hello.
I would like to draw a similar figure as Fig1D shown in your published paper (Alkan et al., 2022) for validation, but I am having difficulty in getting the list of RP-rRNA proximity positions.
The output from running ARF:::mouse_gsea_sets_RP gave a list of positions, so I initially thought the ones without 'Rand' substring on ont column (360 sites) are the contact points. However, when I compared the positions to the highlighted regions on Fig1D, they seems different. 
(+ could you explain what the columns in the output of RF:::RP_proximity_mouse_df mean?)
<img width="196" alt="image" src="https://user-images.githubusercontent.com/34761240/183832910-0608ddcd-49ae-4ab4-abc2-e42cdc70ba93.png">

**Comment by ferhatalkan** [comment]
Hi, 
The Fig1D from the paper do not highlight any specific contact points, it is only highlighting some manually selected positions!
When it comes to  ARF:::mouse_gsea_sets_RP, second column is indeed the contact points for the proteins given in the 1st column. About ARF:::RP_proximity_mouse_df , this is the measured minimum distance (in Angstrom) between every rRNA nt and RP that are given in rows&columns.

**Comment by ferhatalkan** [comment]
For each rRNA residue, the minimum distance to all 82 ribosomal proteins was calculated in angstroms (Å), using the N1 atom and alpha carbon atoms as references for RNA and protein respectively.
