### ISSUE TITLE
Drosophila Ribosomes

### ISSUE THREAD

**Issue by hector3500** [fallerlab/ARF#6]
Hello

I want to use this analysis for drosophila. I'm guessing I could just align my reads to drosophila rRNA if I provide the fasta files, but from there would I be able to go any further? 

Thanks

**Comment by IvonaPYF** [comment]
apologies in advance for jumping in to reply- as I am interested to use ARF for different organism as well- it seems alignment to rRNA is done independently of the pipeline anyway. Then first step that pipeline handles, is positional quantification of rRNA fragment using HelloRanges package, with your aligned .bam file (or .bedGraph) as an input. 
Next step involves creating organism-specific RP–rRNA proximity matrix and from the paper, it seems this was created by Bio3D? 
I guess my side question would also be, which species do you plan to add soon?

**Comment by ferhatalkan** [comment]
Hi all! We are currently wrapping up the new version that is compatible with ANY organism.  

For drosophila or any other organism, you will be able to choose the corresponding ribosome structure with PDB id and run your predictions. If there is no ribosome structure available for your organism, you will still be able to choose a PDB structure that you think is closest to your organism, provide your rRNA sequences and run dripARF based on the other structure. I wish I could give a release timeline but unfortunately not possible.

If you would like to perform your predictions asap, you can reach us by email for potential collobarations.

**Comment by hector3500** [comment]
Amazing, thanks for the info. I'll send you an email.
