### ISSUE TITLE
Does it matter which aligner I am using?

### ISSUE THREAD

**Issue by ashakru** [fallerlab/ARF#7]
Hi, thanks for developing such an interesting tool! It was great to see your poster during the Ribosome Heterogeneity meeting at the Royal Society! 

I would like to give dripARF a go but I'm wondering whether there any preference regarding the aligner? I noticed that in [the paper](https://academic.oup.com/nar/article/50/16/e95/6605319#371756010) TopHat was used with the following parameters `-n 2 --no-novel-juncs --no-novel-indels --no-coverage-search --segment-length 25`. Sadly, TopHat is quite slow and with a large dataset I have, it will be painful to run. Do you have any experience with other aligners (eg. HISAT)? Any particular tags in BAM needed?

**Comment by ferhatalkan** [comment]
Hello Joanna, thank you for your interest in our tool. For the alignments, you can choose any aligner as long as you align to the right rRNA sequences and disable junctions and indels. Another thing is running dripARF with bam files is quite inefficient, so, I suggest using bedtools genomecov to create bedGraph files after the alignment step, for summarizing the read coverages on rRNAs.

**Comment by ashakru** [comment]
Amazing, that's super helpful. Many thanks for quick reply!
