### ISSUE TITLE
Error during GSEA analysis

### ISSUE THREAD

**Issue by whildencm** [fallerlab/ARF#8]
Hi! I've gotten everything installed and am trying to run DRIP-ARF on the test data provided here. The program begins running smoothly, but then I encounter this error (full output attached). I'm wondering if you all may have seen this before/ know what could be causing it. Thanks!
[ARF_error.txt](https://github.com/fallerlab/ARF/files/14042658/ARF_error.txt)

**Comment by ferhatalkan** [comment]
Hi. We have seen this before. It's due to external package version differences. Please see this post on previously solved issue  #4

**Comment by whildencm** [comment]
Thanks-- I cloned and replaced those lines. However, this might be a silly question, I don't really understand how to run it this way. Previously, I just had ARF installed in my R environment and ran the wrapper function-- all from the command line. Do I now run the R_platform.R script in my environment and then call the wrapper function? Thanks

**Comment by ferhatalkan** [comment]
Hi again. After cloning the repository (downloading it as a whole) and making the necessary changes, you would need to reinstall it from that local copy, using a similar command as before, which would be something like this:

install.packages("devtools")
library(devtools)
my_cloned_library_build = devtools::build("~/put/the/package/path/here")
devtools::install_local(my_cloned_library_build)
library(ARF)
